POST http://127.0.0.1:1234/test/run
Content-Type: application/json

{
  "ratePerSecond": 2,
  "testCount": 500,
  "processingTimeMillis": 60000
}

# 4,900
# parallelRequests=5

250 сек + 60 сек

2 -> 1 cек
3 -> 2
5 -> 3
7 -> 4
9 -> 5
...
n*2 - 1 = n
 -> 120 - 1 = 60

  -> 60 sec


3
5
4,9

1 / 4,9 = 0.2 запроса в секунду

5 * 0,2 = 1 <- запрос в сек мы можем делать

Каждая сек +1 в очередь.
60 - выполнилось
60.. - ушли по processingTimeMillis.

59
59

60
60 <- берем?



начиная с 1 секунды, у нас за одну секунду + 1 чел обработан, + 1 в очереди.
каждую следующую секунду самый первый клиент в очереди ждал на 1 секунду дольше первого клиента в очереди на прошлой секунде
когда запроцессилось 60, все люди в очереди ждали 60, 61, 62, 63...